### ISSUE TITLE
Disambiguate signature of module definition from signature of module body source

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#125]
Right now we address Common Modules in caches by a `ModuleId`, which is basically a hash of their source code. However, it is sometimes more appropriate to cache by the `ModuleDefinition`, which wraps the source code inputs and includes things like the input/output keys, the `Affinity` and so on.

There probably needs to be some split along the lines of:

- `ModuleId`: Hash of the full `ModuleDefinition`
- `ModuleBodyId`: Hash of just the module's source code

**Comment by jsantell** [comment]
The larger architecture is changing, closing issues not related to current slate of work
