### ISSUE TITLE
Docker builds fail with dependabot PRs

### ISSUE THREAD

**Issue by jsantell** [commontoolsinc/system#134]
The docker build CI step is failing for dependabot PRs: https://github.com/commontoolsinc/system/actions/runs/10462333921/job/28972387436?pr=128

> Run google-github-actions/auth@v2
Error: google-github-actions/auth failed with: the GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"! If you are specifying input values via GitHub secrets, ensure the secret is being injected into the environment. By default, secrets are not passed to workflows triggered from forks, including Dependabot.

**Comment by cdata** [comment]
@commontoolsinc/exadev can you take a look at this?

**Comment by wfaithfull** [comment]
@Mearman I thought you already merged something last week that skipped the auth & push step for these dependabot PRs since they can't access the credentials?

**Comment by Mearman** [comment]
oh you beat me to mentioning this @wfaithfull

**Comment by wfaithfull** [comment]
I believe this is all resolved now.
