### ISSUE TITLE
Docker build that passes in PR fails on main

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#135]
I just landed PR #105. In this PR, Docker builds appeared to pass. After landing the PR on main, the Docker build failed. We should investigate what happened.

Docker build failing after PR lands on `main`: https://github.com/commontoolsinc/system/actions/runs/10513827137

Docker build passing in PR: https://github.com/commontoolsinc/system/actions/runs/10513231062

**Comment by cdata** [comment]
@commontoolsinc/exadev can you look into this one?

**Comment by wfaithfull** [comment]
Sure thing. At first glance looks like cargo binstall has failed. We'll investigate in the morning.

**Comment by Mearman** [comment]
from [L1923](https://github.com/commontoolsinc/system/actions/runs/10513827137/job/29130257121#step:8:1929)
```sh
34.06     = note: perhaps two different versions of crate `gix_date` are being used?
```
I wonder if it's a stale cache

**Comment by wfaithfull** [comment]
There is some flake here as it has passed on a rerun:

https://github.com/commontoolsinc/system/actions/runs/10513827137

**Comment by wfaithfull** [comment]
And I don't see any `cargo` changes in the diff: https://github.com/commontoolsinc/system/commit/3652057d8cdecc33f085d8cb50c7b7167a3a75f5#diff-7d4d82c669be98a5d5c18021398c4a2ddd6b0dae9233958f192ae943ae0fc238

I think you are right Joe, it must be some kind of caching issue.

https://github.com/commontoolsinc/system/blob/main/.github/workflows/docker.yml#L98
https://docs.docker.com/reference/cli/docker/buildx/build/#cache-from

Some links for more investigation.

**Comment by wfaithfull** [comment]
```
ERROR: failed to solve: debian:bookworm-slim: failed to resolve source metadata for docker.io/library/debian:bookworm-slim: failed to do request: Head "https://registry-1.docker.io/v2/library/debian/manifests/bookworm-slim": net/http: TLS handshake timeout
```

Related flakiness from another failed build today.
