### ISSUE TITLE
Use nix in CI

### ISSUE THREAD

**Issue by jsantell** [commontoolsinc/system#173]
We have a `devshell.nix` for managing system dependencies. Currently, our CI is not using this, manually pulling in its dependencies. While continuing to explore if devshell is suitable for this project, we should start to integrate nix more to validate that.

* Set up a nix build action in CI along existing actions. This will ensure that devshell stays up to date. (#178)
* Evaluate considerations needed to support macos. Some packages (e.g. chromium) are not available for `aarch64-darwin`. Initial work: https://github.com/commontoolsinc/system/pull/180
* Figure out how dependabot can help with updates https://github.com/commontoolsinc/system/issues/146

If these steps go well, we can use nix for all actions in CI, as well as Docker builds (replacing the Makefile)

Some additional TODOs: https://github.com/commontoolsinc/system/pull/180#pullrequestreview-2303754101

**Comment by Mearman** [comment]
Dev containers may be a solution for people on MacOS

**Comment by jsantell** [comment]
There are room for improvements, but relevant GH actions are now backed by nix
