### ISSUE TITLE
fix: Resolve GitHub App pipeline permissions

### ISSUE THREAD

**Issue by Mearman** [commontoolsinc/system#175]
Looks like the [GitHub App](https://github.com/apps/common-tools-ci) needs `Actions Write` permission to `POST` to the workflow dispatch endpoint.
see failure here: https://github.com/commontoolsinc/system/actions/runs/10797604991/job/29976844271#step:3:15
 
reference: https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#:~:text=POST%20/repos/%7Bowner%7D/%7Brepo%7D/actions/workflows/%7Bworkflow_id%7D/dispatches

**Comment by Mearman** [comment]
@jkomoros, @seefeldb, or @cdata, could you please grant me access to the org to modify [Workflow Permissions](https://github.com/organizations/commontoolsinc/settings/actions) and install the [GitHub App](https://github.com/apps/common-tools-ci)?

**Comment by WillOnGit** [comment]
@Mearman this is resolved now, right?
