### ISSUE TITLE
Implement our own stubs for `wasi:*` APIs

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#20]
Currently when we link Wasm Components in the server-side sandbox, we link `wasi:*` APIs using the native Rust implementations found in the https://github.com/bytecodealliance/wasmtime repo. This was nice to get going quickly, but the package implementations are all real! We should replace them with mostly-stubbed custom implementations of the various `wasi:*` packages that may be required by e.g., Starling Monkey.

**Comment by jsantell** [comment]
Using stubs via `wasi-virt` in basic worlds
