### ISSUE TITLE
`WasmtimeInterpreter` should re-use `WasmtimeCompiler` internally to compile VM components

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#36]
Although `WasmtimeInterpreter` (as the name implies) is intended for fast-feedback-loop interpreting of scripts, it still has a compile step for the VM that is doing the interpreting. Right now we have parallel compilation passes in `WasmtimeInterpreter` and `WasmtimeCompiler`, but it plausible improvement is for `WasmtimeCompiler` to be made generic over the bindings that compiles a component against. This would allow us to make `WasmtimeInterpreter` a thin envelope over `WasmtimeCompiler`.

**Comment by jsantell** [comment]
The larger architecture is changing, closing issues not related to current slate of work
