### ISSUE TITLE
Figure out why ComponentizeJS@0.10.0 broke the build

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#45]
Looks like [ComponentizeJS@0.10.0](https://github.com/bytecodealliance/ComponentizeJS/releases/tag/0.10.0) (released yesterday) breaks our build. Let's figure out why!

Example build: https://github.com/commontoolsinc/system/actions/runs/9965092850/job/27534800969

**Comment by jsantell** [comment]
Using `wasm_component_layer` means goodbye jco/componentize-js
