### ISSUE TITLE
renovate CI for `system` containers

### ISSUE THREAD

**Issue by Mearman** [commontoolsinc/system#46]
> @cdata https://discord.com/channels/1232452732963655720/1263178332522942675/1263185906127605872
> Within system we have made a pass at containerizing things, but the pass is stale and we don't have any automation to keep us diligent and ensure it still works (I'm almost certain that the Dockerfiles are out of date at this time).
>
> So, one low-hanging-fruit would be adding a Github Action to system that builds our containers (fixing any broken Dockerfiles along the way).

- [ ] runtime
  - [ ] maintenance on [common-runtime/Dockerfile](https://github.com/commontoolsinc/system/blob/main/rust/common-runtime/Dockerfile)
  - [ ] GitHub Job for [common-runtime/Dockerfile](https://github.com/commontoolsinc/system/blob/main/rust/common-runtime/Dockerfile)
- [ ] builder
  - [ ] #51
  - [ ] GitHub Workflow for [common-builder/Dockerfile](https://github.com/commontoolsinc/system/blob/main/rust/common-builder/Dockerfile)
- [ ] build updated [compose file](https://github.com/commontoolsinc/system/blob/main/compose.yaml)

**Comment by cdata** [comment]
We also have an out-of-date [`compose.yaml`](https://github.com/commontoolsinc/system/blob/main/compose.yaml)

**Comment by WillOnGit** [comment]
We have a proposed draft change in our fork of `system` which we'll tidy up and submit as a PR this afternoon.

**Comment by WillOnGit** [comment]
Related to https://github.com/commontoolsinc/infrastructure/issues/8

**Comment by wfaithfull** [comment]
I think this can be considered done, as we are now working on deployments of the containers that this issue references, and #65 actually deletes the old Dockerfiles anyway.
