### ISSUE TITLE
wireit intermittently fails

### ISSUE THREAD

**Issue by jsantell** [commontoolsinc/system#60]
Seeing failures on wasm32 builds related to common-wit/npm/wireit.

Some failures from (presumably benign) dependabot updates:

* https://github.com/commontoolsinc/system/actions/runs/10050122850/job/27870835902?pr=56
* https://github.com/commontoolsinc/system/actions/runs/10050092732/job/27870858624?pr=53

Eventually retrying leads to success: https://github.com/commontoolsinc/system/actions/runs/10050092732/job/27871193920?pr=53

**Comment by jsantell** [comment]
Seeing here in native builds too https://github.com/commontoolsinc/system/actions/runs/10084515903/job/27883707638?pr=61

**Comment by Mearman** [comment]
I can have a look at this if you want? I've had a fair bit of experience in the Breadboard repo.
