### ISSUE TITLE
add `README` for `rust/Dockerfile`

### ISSUE THREAD

**Issue by Mearman** [commontoolsinc/system#65]
Also: if there is a Dockerfile out of context on its own in a folder somewhere, do add a `README.md` to explain its meaning!

_Originally posted by @cdata in https://github.com/commontoolsinc/system/pull/62#discussion_r1690394769_

**Comment by WillOnGit** [comment]
Also CDKTF repo.

**Comment by WillOnGit** [comment]
Superseded by #104
