### ISSUE TITLE
create wrapper package for `module/scripts/generate-wit-module.sh`

### ISSUE THREAD

**Issue by Mearman** [commontoolsinc/system#66]
> as an alternative, I could wrap it in its own package so it can be called with npx?

SGTM!

_Originally posted by @cdata in https://github.com/commontoolsinc/system/pull/62#discussion_r1690395713_

**Comment by WillOnGit** [comment]
Leaving for now as may end up out-of-scope due to @jsantell's upcoming changes.

**Comment by wfaithfull** [comment]
@jsantell deleted this script in b29fd3690db363a6677b81d402f8c99da768a0b4 and moved `wit` stuff up to a top level concern - I think this is no longer relevant. If no objections in next 24h I will look to close this.
