### ISSUE TITLE
Unbundle Runtime into a collection of traits

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#69]
Currently we have a set of traits that describe the various preparation and instantiation constraints of a Common Module. As we've grown the scope of what a Runtime may or may not do, it seems likely that we would benefit from unbundling it into a series of traits that express Runtimes that:

- Work with compiled modules
- Work with interpreted modules
- Run modules locally
- Run modules remotely
- etc.

**Comment by jsantell** [comment]
I believe #105 handled this, closing
