### ISSUE TITLE
Make a compiled Common Module that uses Boa instead of Starling Monkey

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#71]
Our `common-builder` currently relies on `jco` (and transitively `wizer`) to produce a "compiled" Wasm Component from a JavaScript source file. In #22 we introduced a Wasm Component that embodies the Boa JavaScript interpreter. The nascent success of this work suggests that we maybe be able to substitute Boa for Starling Monkey and get similar results while cutting down binary size and homogenizing Common Module / Common Script runtime environments along the way. So, this issue covers attempting to use Boa for compiled Common Modules.

**Comment by jsantell** [comment]
Currently focused on the boa VM
