### ISSUE TITLE
`cargo check` is very slow - can we make it faster?

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#80]
Right now `cargo check` is pretty slow.

`cargo check --target wasm32-unknown-unknown --timings` shows us this breakdown:

![image](https://github.com/user-attachments/assets/6f6334d2-f772-47a9-9fa7-02bcde5525c5)

15s is pretty slow. It certainly makes the feedback loop in a text editor worse. Can we fix it?

**Comment by jsantell** [comment]
I believe this was fixed in #94; common_runtime's build.rs now appropriately caches things
