### ISSUE TITLE
`NewType` derive macro pre-empts `TryFrom` impl on struct

### ISSUE THREAD

**Issue by cdata** [commontoolsinc/system#96]
Our `NewType` derive macro automatically implements bi-directional `From` for outer->inner and inner->outer types. However, this is a little presumptive. This means that `TryFrom` cannot be implemented for a type that derives `NewType`. It can be nice to use `TryFrom` for cases when the inner value must be validated before it can be wrapped in the outer type.

It's probably fine to cut the bi-directional `From` implementation, but maybe we can make the macro fancier so that the derivee can opt-out.

**Comment by jsantell** [comment]
Fixed in #106
